export const GET_LINKAGES_REQ = 'GET_LINKAGES_REQ';
export const GET_LINKAGES_SUCCESS = 'GET_LINKAGES_SUCCESS';
export const GET_LINKAGES_FAILURE = 'GET_LINKAGES_FAILURE';

export const ADD_LINKAGE_REQ = 'ADD_LINKAGE_REQ';
export const ADD_LINKAGE_SUCCESS = 'ADD_LINKAGE_SUCCESS';
export const ADD_LINKAGE_FAILURE = 'ADD_LINKAGE_FAILURE';

export const EDIT_LINKAGE_REQ = 'EDIT_LINKAGE_REQ';
export const EDIT_LINKAGE_SUCCESS = 'EDIT_LINKAGE_SUCCESS';
export const EDIT_LINKAGE_FAILURE = 'EDIT_LINKAGE_FAILURE';

export const SORT_LINKAGES = 'SORT_LINKAGES';

export const GET_SHARING_DETAILS_REQ = 'GET_SHARING_DETAILS_REQ';
export const GET_SHARING_DETAILS_SUCCESS = 'GET_SHARING_DETAILS_SUCCESS';
export const GET_SHARING_DETAILS_FAILURE = 'GET_SHARING_DETAILS_FAILURE';

export const CLEAR_SHARING_DETAILS = 'CLEAR_SHARING_DETAILS';

export const SHARE_LINKAGE_REQ = 'SHARE_LINKAGE_REQ';
export const SHARE_LINKAGE_SUCCESS = 'SHARE_LINKAGE_SUCCESS';
export const SHARE_LINKAGE_FAILURE = 'SHARE_LINKAGE_FAILURE';

export const MOVE_LINKAGE_REQ = 'MOVE_LINKAGE_REQ';
export const MOVE_LINKAGE_SUCCESS = 'MOVE_LINKAGE_SUCCESS';
export const MOVE_LINKAGE_FAILURE = 'MOVE_LINKAGE_FAILURE';

export const DELETE_LINKAGE_REQ = 'DELETE_LINKAGE_REQ';
export const DELETE_LINKAGE_SUCCESS = 'DELETE_LINKAGE_SUCCESS';
export const DELETE_LINKAGE_FAILURE = 'DELETE_LINKAGE_FAILURE';

export const GET_LINKAGE_PATH_REQ = 'GET_LINKAGE_PATH_REQ';
export const GET_LINKAGE_PATH_SUCCESS = 'GET_LINKAGE_PATH_SUCCESS';
export const GET_LINKAGE_PATH_FAILURE = 'GET_LINKAGE_PATH_FAILURE';
